### ISSUE TITLE
cloudWatch example?

### ISSUE THREAD

**Issue by mwawrusch** [justinram11/serverless-aws-batch#9]
Could you provide a cloud watch example? I need to run the batch every 90 minutes and am a little bit lost how to correctly configure this.
Thanks

**Comment by mwawrusch** [comment]
So, after a bit of digging (and some misleading blog information) it seems that this:

```
    events:
      - schedule: cron(0/90 * * * ? *)
```

is all there is and serverless takes care of the rest

**Comment by justinram11** [comment]
Yup, adding that to the function in `serverless.yml` should do the trick.

The other thing you could try if you don't care about the _exact_ time it runs (just that it runs every 90 minutes) is:

```
- schedule: rate(90 minutes)
```
